# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings
title: BZR
SEOTitle: BruceZhao's Blog
author: Bruce Zhao
timezone: Asia/Shanghai
paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM                       # use Github Flavored Markdown !important
  
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# 国内用多说
# disqus: brucezhaor

#Google Analytics https://developers.google.com/analytics/devguides/collection/analyticsjs/
#去_layout/default.html的头文件中去设置.
#google_analytics_id: UA-72808482-1
#google_analytics_domain: auto

# 自定义永久链接
permalink: /blog/:year/:month/:day/:title/

#默认底图
header-img: /img/default-bg.jpg

RSS: feed.xml
categories_path: categories
tags_path: tags
archive_path: archives
about_path: about

BASE_PATH:


# SNS settings

weibo_username:     brucezhaor
facebook_username:     BruceZhaoR
github_username:    BruceZhaoR
google_username:  101167914127123982138/posts
RSS: feed.xml
email: brucezhaor2016@gmail.com
linkedin: brucezhaor

anchorjs: true                          # 修改在default.html->footer


# 评论系统
# Duoshuo settings
duoshuo_username: brucezhaor
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing
url: "http://brucezhaor.github.io" 

# page Sidebar settings
sidebar-about-description: "A future technique geek."
sidebar-avatar: /img/me2.jpg     # img前面加`/`绝对引用。



# Friends
friends: [
	{   
        title: "R学习社区",
        href: "http://bzrlc.github.io/about/"
	},{
        title: "Hux-模板来源",
        href: "https://github.com/Huxpro/huxpro.github.io"
	},{
        title: "谢益辉",
        href: "http://yihui.name"
	},{
        title: "落园",
        href: "http://www.loyhome.cn/"
    },{
        title: "刘思喆",
        href: "http://www.bjt.name/"
    },{
        title: "邱怡轩",
        href: "http://yixuan.cos.name/cn/"
	},{
        title: "JRQ 西南交大",
        href: "http://ruiqiangjiao.github.io/"
	},{
        title: "MenBin 东财应统",
        href: "http://binmen.github.io/blog"
	}
]



